[theme]
primaryColor = "#162E20"
backgroundColor = "#F3F4F1"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#162E20"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
